import {
  DataCenter,
  Rack,
  Server,
  Client,
  ServerAllocation,
  MaintenanceRecord,
  Organization,
  User,
  ActivityLog,
  NotificationItem,
  ReportItem
} from '../types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'National Informatics Infrastructure Corp',
    code: 'NIIC-IN',
    type: 'Government',
    primaryContact: 'Dr. Alok Verma',
    email: 'contact@niic.gov.in',
    phone: '+91 11 2436 0001',
    activeCentersCount: 3,
    headquarters: 'New Delhi, India',
    registeredDate: '2023-01-15',
    status: 'Active'
  },
  {
    id: 'org-2',
    name: 'Bharat Petroleum Cloud Grid',
    code: 'BPCG',
    type: 'Public Sector',
    primaryContact: 'Sunita Sharma',
    email: 'infra@bharatpetroleum.in',
    phone: '+91 22 2271 3000',
    activeCentersCount: 2,
    headquarters: 'Mumbai, Maharashtra',
    registeredDate: '2023-04-10',
    status: 'Active'
  },
  {
    id: 'org-3',
    name: 'Unified Payments Enterprise Services',
    code: 'UPES-FIN',
    type: 'Enterprise',
    primaryContact: 'Rohan Mehra',
    email: 'ops@upes-payments.com',
    phone: '+91 80 4012 8899',
    activeCentersCount: 4,
    headquarters: 'Bengaluru, Karnataka',
    registeredDate: '2023-08-22',
    status: 'Active'
  },
  {
    id: 'org-4',
    name: 'SkyRoute Logistics Network',
    code: 'SKRL',
    type: 'Enterprise',
    primaryContact: 'Neha Iyer',
    email: 'it-support@skyroute.co.in',
    phone: '+91 40 6677 2200',
    activeCentersCount: 2,
    headquarters: 'Hyderabad, Telangana',
    registeredDate: '2024-02-18',
    status: 'Active'
  }
];

export const INITIAL_DATA_CENTERS: DataCenter[] = [
  {
    id: 'dc-1',
    name: 'BHARATDC Mumbai West (MUM-1)',
    code: 'MUM-1',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Plot 42, TTC Industrial Area, MIDC, Navi Mumbai, 400705',
    totalRacks: 48,
    totalServers: 420,
    activeServers: 310,
    powerCapacityKw: 2400,
    status: 'Active',
    manager: 'Rajesh Verma',
    contactPhone: '+91 22 4589 1100'
  },
  {
    id: 'dc-2',
    name: 'BHARATDC Delhi NCR (DEL-1)',
    code: 'DEL-1',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    address: 'Sector 62, Electronic City, Noida, 201309',
    totalRacks: 36,
    totalServers: 310,
    activeServers: 220,
    powerCapacityKw: 1800,
    status: 'Active',
    manager: 'Pooja Kashyap',
    contactPhone: '+91 120 488 9200'
  },
  {
    id: 'dc-3',
    name: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    code: 'BLR-1',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    address: 'Whitefield Main Road, EPIP Zone, Bengaluru, 560066',
    totalRacks: 60,
    totalServers: 540,
    activeServers: 460,
    powerCapacityKw: 3200,
    status: 'Active',
    manager: 'Karthik Raman',
    contactPhone: '+91 80 6123 4455'
  },
  {
    id: 'dc-4',
    name: 'BHARATDC Hyderabad HITEC (HYD-1)',
    code: 'HYD-1',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    address: 'Financial District, Nanakramguda, Hyderabad, 500032',
    totalRacks: 32,
    totalServers: 260,
    activeServers: 195,
    powerCapacityKw: 1500,
    status: 'Active',
    manager: 'Srinivas Rao',
    contactPhone: '+91 40 4500 7890'
  },
  {
    id: 'dc-5',
    name: 'BHARATDC Chennai Coast (CHE-1)',
    code: 'CHE-1',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    address: 'Old Mahabalipuram Road, Siruseri SIPCOT, Chennai, 603103',
    totalRacks: 24,
    totalServers: 180,
    activeServers: 95,
    powerCapacityKw: 1200,
    status: 'Planned',
    manager: 'Ananya Sundaram',
    contactPhone: '+91 44 2811 5000'
  }
];

export const INITIAL_RACKS: Rack[] = [
  {
    id: 'rack-1',
    rackNumber: 'Rack-A01',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    room: 'Server Hall 1',
    row: 'Row A',
    totalUnits: 42,
    usedUnits: 36,
    maxPowerKw: 12,
    currentPowerKw: 8.4,
    status: 'Available',
    temperatureC: 21.5
  },
  {
    id: 'rack-2',
    rackNumber: 'Rack-A02',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    room: 'Server Hall 1',
    row: 'Row A',
    totalUnits: 42,
    usedUnits: 42,
    maxPowerKw: 12,
    currentPowerKw: 11.2,
    status: 'Full',
    temperatureC: 22.8
  },
  {
    id: 'rack-3',
    rackNumber: 'Rack-B05',
    dataCenterId: 'dc-2',
    dataCenterName: 'BHARATDC Delhi NCR (DEL-1)',
    room: 'Server Hall East',
    row: 'Row B',
    totalUnits: 42,
    usedUnits: 28,
    maxPowerKw: 10,
    currentPowerKw: 6.2,
    status: 'Available',
    temperatureC: 20.8
  },
  {
    id: 'rack-4',
    rackNumber: 'Rack-C03',
    dataCenterId: 'dc-3',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    room: 'Main Data Hall',
    row: 'Row C',
    totalUnits: 42,
    usedUnits: 38,
    maxPowerKw: 14,
    currentPowerKw: 9.8,
    status: 'Available',
    temperatureC: 21.0
  },
  {
    id: 'rack-5',
    rackNumber: 'Rack-C04',
    dataCenterId: 'dc-3',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    room: 'Main Data Hall',
    row: 'Row C',
    totalUnits: 42,
    usedUnits: 20,
    maxPowerKw: 14,
    currentPowerKw: 4.5,
    status: 'Under Maintenance',
    temperatureC: 24.2
  },
  {
    id: 'rack-6',
    rackNumber: 'Rack-D01',
    dataCenterId: 'dc-4',
    dataCenterName: 'BHARATDC Hyderabad HITEC (HYD-1)',
    room: 'Hall Gamma',
    row: 'Row D',
    totalUnits: 42,
    usedUnits: 30,
    maxPowerKw: 10,
    currentPowerKw: 7.1,
    status: 'Available',
    temperatureC: 21.2
  }
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'NIC Digital Portal Services',
    organization: 'National Informatics Infrastructure Corp',
    email: 'cloud-tier1@nic.in',
    phone: '+91 11 2430 5500',
    contactPerson: 'Sanjay Deshmukh',
    billingType: 'Annual',
    activeAllocationsCount: 14,
    joinedDate: '2023-02-01',
    status: 'Active',
    slaTier: 'Mission Critical'
  },
  {
    id: 'client-2',
    name: 'State Energy Grid Automation',
    organization: 'Bharat Petroleum Cloud Grid',
    email: 'grid-telemetry@bharatpetroleum.in',
    phone: '+91 22 2840 9100',
    contactPerson: 'Arun Kulkarni',
    billingType: 'Quarterly',
    activeAllocationsCount: 8,
    joinedDate: '2023-05-15',
    status: 'Active',
    slaTier: 'Premium'
  },
  {
    id: 'client-3',
    name: 'FastPay Gateway Solutions',
    organization: 'Unified Payments Enterprise Services',
    email: 'production-ops@fastpay-infra.com',
    phone: '+91 80 4900 1122',
    contactPerson: 'Deepak Saxena',
    billingType: 'Monthly',
    activeAllocationsCount: 22,
    joinedDate: '2023-09-01',
    status: 'Active',
    slaTier: 'Mission Critical'
  },
  {
    id: 'client-4',
    name: 'AeroTracking Fleet Telematics',
    organization: 'SkyRoute Logistics Network',
    email: 'fleet-servers@skyroute.co.in',
    phone: '+91 40 6688 3344',
    contactPerson: 'Kavita Menon',
    billingType: 'Monthly',
    activeAllocationsCount: 6,
    joinedDate: '2024-03-01',
    status: 'Active',
    slaTier: 'Standard'
  },
  {
    id: 'client-5',
    name: 'Rural Health Record Archive',
    organization: 'National Informatics Infrastructure Corp',
    email: 'health-archive@nic.gov.in',
    phone: '+91 11 2439 8811',
    contactPerson: 'Vikram Joshi',
    billingType: 'Annual',
    activeAllocationsCount: 4,
    joinedDate: '2024-05-10',
    status: 'Active',
    slaTier: 'Standard'
  }
];

export const INITIAL_SERVERS: Server[] = [
  {
    id: 'srv-101',
    assetTag: 'BDC-SRV-101',
    hostname: 'mum1-node-01.bharatdc.net',
    serialNumber: 'SN-DELL-99210',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    rackId: 'rack-1',
    rackNumber: 'Rack-A01',
    unitPosition: 'U01 - U02',
    model: 'Dell PowerEdge R750',
    cpu: '2x Intel Xeon Gold 6348 (56 Cores)',
    ramGb: 256,
    storageTb: 16,
    primaryIp: '10.14.20.11',
    status: 'In Use',
    allocatedClientId: 'client-1',
    clientName: 'NIC Digital Portal Services',
    purchaseDate: '2023-03-10',
    warrantyExpiry: '2026-03-10',
    notes: 'Primary database node for civic services portal'
  },
  {
    id: 'srv-102',
    assetTag: 'BDC-SRV-102',
    hostname: 'mum1-node-02.bharatdc.net',
    serialNumber: 'SN-DELL-99211',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    rackId: 'rack-1',
    rackNumber: 'Rack-A01',
    unitPosition: 'U03 - U04',
    model: 'Dell PowerEdge R750',
    cpu: '2x Intel Xeon Gold 6348 (56 Cores)',
    ramGb: 256,
    storageTb: 16,
    primaryIp: '10.14.20.12',
    status: 'In Use',
    allocatedClientId: 'client-1',
    clientName: 'NIC Digital Portal Services',
    purchaseDate: '2023-03-10',
    warrantyExpiry: '2026-03-10',
    notes: 'Secondary replica node'
  },
  {
    id: 'srv-103',
    assetTag: 'BDC-SRV-103',
    hostname: 'mum1-node-03.bharatdc.net',
    serialNumber: 'SN-HPE-48192',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    rackId: 'rack-1',
    rackNumber: 'Rack-A01',
    unitPosition: 'U05 - U06',
    model: 'HPE ProLiant DL380 Gen10',
    cpu: '2x AMD EPYC 7763 (128 Cores)',
    ramGb: 512,
    storageTb: 32,
    primaryIp: '10.14.20.15',
    status: 'Available',
    purchaseDate: '2023-07-15',
    warrantyExpiry: '2026-07-15',
    notes: 'Cleaned and ready for client onboarding'
  },
  {
    id: 'srv-104',
    assetTag: 'BDC-SRV-104',
    hostname: 'mum1-node-04.bharatdc.net',
    serialNumber: 'SN-CISCO-8831',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    rackId: 'rack-2',
    rackNumber: 'Rack-A02',
    unitPosition: 'U10 - U11',
    model: 'Cisco UCS C220 M5',
    cpu: '2x Intel Xeon Silver 4214R',
    ramGb: 128,
    storageTb: 8,
    primaryIp: '10.14.20.24',
    status: 'Under Maintenance',
    purchaseDate: '2023-01-20',
    warrantyExpiry: '2026-01-20',
    notes: 'Memory module diagnostic in progress'
  },
  {
    id: 'srv-105',
    assetTag: 'BDC-SRV-105',
    hostname: 'del1-compute-01.bharatdc.net',
    serialNumber: 'SN-DELL-88301',
    dataCenterId: 'dc-2',
    dataCenterName: 'BHARATDC Delhi NCR (DEL-1)',
    rackId: 'rack-3',
    rackNumber: 'Rack-B05',
    unitPosition: 'U01 - U02',
    model: 'Dell PowerEdge R650',
    cpu: '2x Intel Xeon Platinum 8358',
    ramGb: 384,
    storageTb: 24,
    primaryIp: '10.22.10.11',
    status: 'In Use',
    allocatedClientId: 'client-2',
    clientName: 'State Energy Grid Automation',
    purchaseDate: '2023-05-18',
    warrantyExpiry: '2026-05-18',
    notes: 'Grid telemetry processing cluster'
  },
  {
    id: 'srv-106',
    assetTag: 'BDC-SRV-106',
    hostname: 'del1-compute-02.bharatdc.net',
    serialNumber: 'SN-DELL-88302',
    dataCenterId: 'dc-2',
    dataCenterName: 'BHARATDC Delhi NCR (DEL-1)',
    rackId: 'rack-3',
    rackNumber: 'Rack-B05',
    unitPosition: 'U03 - U04',
    model: 'Dell PowerEdge R650',
    cpu: '2x Intel Xeon Platinum 8358',
    ramGb: 384,
    storageTb: 24,
    primaryIp: '10.22.10.12',
    status: 'Available',
    purchaseDate: '2023-05-18',
    warrantyExpiry: '2026-05-18',
    notes: 'Reserve node for peak winter load'
  },
  {
    id: 'srv-107',
    assetTag: 'BDC-SRV-107',
    hostname: 'blr1-edge-01.bharatdc.net',
    serialNumber: 'SN-SUPER-7712',
    dataCenterId: 'dc-3',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    rackId: 'rack-4',
    rackNumber: 'Rack-C03',
    unitPosition: 'U01 - U02',
    model: 'Supermicro Ultra SYS-2029U',
    cpu: '2x Intel Xeon Gold 6248R',
    ramGb: 512,
    storageTb: 48,
    primaryIp: '10.30.40.10',
    status: 'In Use',
    allocatedClientId: 'client-3',
    clientName: 'FastPay Gateway Solutions',
    purchaseDate: '2023-09-05',
    warrantyExpiry: '2026-09-05',
    notes: 'Low-latency financial clearing ledger node'
  },
  {
    id: 'srv-108',
    assetTag: 'BDC-SRV-108',
    hostname: 'blr1-edge-02.bharatdc.net',
    serialNumber: 'SN-SUPER-7713',
    dataCenterId: 'dc-3',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    rackId: 'rack-4',
    rackNumber: 'Rack-C03',
    unitPosition: 'U03 - U04',
    model: 'Supermicro Ultra SYS-2029U',
    cpu: '2x Intel Xeon Gold 6248R',
    ramGb: 512,
    storageTb: 48,
    primaryIp: '10.30.40.11',
    status: 'In Use',
    allocatedClientId: 'client-3',
    clientName: 'FastPay Gateway Solutions',
    purchaseDate: '2023-09-05',
    warrantyExpiry: '2026-09-05',
    notes: 'Payment gateway API gateway cluster'
  },
  {
    id: 'srv-109',
    assetTag: 'BDC-SRV-109',
    hostname: 'blr1-edge-03.bharatdc.net',
    serialNumber: 'SN-HPE-11099',
    dataCenterId: 'dc-3',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    rackId: 'rack-5',
    rackNumber: 'Rack-C04',
    unitPosition: 'U08 - U09',
    model: 'HPE ProLiant DL360 Gen10',
    cpu: '1x Intel Xeon Silver 4210',
    ramGb: 64,
    storageTb: 4,
    primaryIp: '10.30.40.88',
    status: 'Not Working',
    purchaseDate: '2022-11-12',
    warrantyExpiry: '2025-11-12',
    notes: 'Power supply unit 1 tripped, chassis unpowered. Awaiting replacement.'
  },
  {
    id: 'srv-110',
    assetTag: 'BDC-SRV-110',
    hostname: 'hyd1-logistics-01.bharatdc.net',
    serialNumber: 'SN-DELL-66201',
    dataCenterId: 'dc-4',
    dataCenterName: 'BHARATDC Hyderabad HITEC (HYD-1)',
    rackId: 'rack-6',
    rackNumber: 'Rack-D01',
    unitPosition: 'U01 - U02',
    model: 'Dell PowerEdge R7525',
    cpu: '2x AMD EPYC 7543 (64 Cores)',
    ramGb: 256,
    storageTb: 20,
    primaryIp: '10.40.15.10',
    status: 'In Use',
    allocatedClientId: 'client-4',
    clientName: 'AeroTracking Fleet Telematics',
    purchaseDate: '2024-03-05',
    warrantyExpiry: '2027-03-05',
    notes: 'GPS real-time ping aggregation server'
  },
  {
    id: 'srv-111',
    assetTag: 'BDC-SRV-111',
    hostname: 'hyd1-logistics-02.bharatdc.net',
    serialNumber: 'SN-DELL-66202',
    dataCenterId: 'dc-4',
    dataCenterName: 'BHARATDC Hyderabad HITEC (HYD-1)',
    rackId: 'rack-6',
    rackNumber: 'Rack-D01',
    unitPosition: 'U03 - U04',
    model: 'Dell PowerEdge R7525',
    cpu: '2x AMD EPYC 7543 (64 Cores)',
    ramGb: 256,
    storageTb: 20,
    primaryIp: '10.40.15.11',
    status: 'Available',
    purchaseDate: '2024-03-05',
    warrantyExpiry: '2027-03-05',
    notes: 'Spare compute node ready for deployment'
  },
  {
    id: 'srv-112',
    assetTag: 'BDC-SRV-112',
    hostname: 'mum1-backup-01.bharatdc.net',
    serialNumber: 'SN-CISCO-7710',
    dataCenterId: 'dc-1',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    rackId: 'rack-2',
    rackNumber: 'Rack-A02',
    unitPosition: 'U15 - U16',
    model: 'Cisco UCS C240 M5',
    cpu: '2x Intel Xeon Gold 5218',
    ramGb: 192,
    storageTb: 60,
    primaryIp: '10.14.20.90',
    status: 'In Use',
    allocatedClientId: 'client-5',
    clientName: 'Rural Health Record Archive',
    purchaseDate: '2023-06-20',
    warrantyExpiry: '2026-06-20',
    notes: 'Encrypted long-term medical document storage node'
  }
];

export const INITIAL_ALLOCATIONS: ServerAllocation[] = [
  {
    id: 'alloc-1',
    serverId: 'srv-101',
    serverHostname: 'mum1-node-01.bharatdc.net',
    assetTag: 'BDC-SRV-101',
    clientId: 'client-1',
    clientName: 'NIC Digital Portal Services',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    assignedDate: '2023-04-01',
    billingCycle: 'Annual',
    purpose: 'Civic Services Master Database',
    bandwidthQuotaTb: 50,
    status: 'Active'
  },
  {
    id: 'alloc-2',
    serverId: 'srv-102',
    serverHostname: 'mum1-node-02.bharatdc.net',
    assetTag: 'BDC-SRV-102',
    clientId: 'client-1',
    clientName: 'NIC Digital Portal Services',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    assignedDate: '2023-04-01',
    billingCycle: 'Annual',
    purpose: 'Civic Services Replica Database',
    bandwidthQuotaTb: 50,
    status: 'Active'
  },
  {
    id: 'alloc-3',
    serverId: 'srv-105',
    serverHostname: 'del1-compute-01.bharatdc.net',
    assetTag: 'BDC-SRV-105',
    clientId: 'client-2',
    clientName: 'State Energy Grid Automation',
    dataCenterName: 'BHARATDC Delhi NCR (DEL-1)',
    assignedDate: '2023-06-01',
    billingCycle: 'Quarterly',
    purpose: 'Power Grid Smart Sensor Collector',
    bandwidthQuotaTb: 20,
    status: 'Active'
  },
  {
    id: 'alloc-4',
    serverId: 'srv-107',
    serverHostname: 'blr1-edge-01.bharatdc.net',
    assetTag: 'BDC-SRV-107',
    clientId: 'client-3',
    clientName: 'FastPay Gateway Solutions',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    assignedDate: '2023-09-15',
    billingCycle: 'Monthly',
    purpose: 'Core Transaction Clearing Node A',
    bandwidthQuotaTb: 100,
    status: 'Active'
  },
  {
    id: 'alloc-5',
    serverId: 'srv-108',
    serverHostname: 'blr1-edge-02.bharatdc.net',
    assetTag: 'BDC-SRV-108',
    clientId: 'client-3',
    clientName: 'FastPay Gateway Solutions',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    assignedDate: '2023-09-15',
    billingCycle: 'Monthly',
    purpose: 'Core Transaction Clearing Node B',
    bandwidthQuotaTb: 100,
    status: 'Active'
  },
  {
    id: 'alloc-6',
    serverId: 'srv-110',
    serverHostname: 'hyd1-logistics-01.bharatdc.net',
    assetTag: 'BDC-SRV-110',
    clientId: 'client-4',
    clientName: 'AeroTracking Fleet Telematics',
    dataCenterName: 'BHARATDC Hyderabad HITEC (HYD-1)',
    assignedDate: '2024-03-10',
    billingCycle: 'Monthly',
    purpose: 'Fleet GPS Geofence Router',
    bandwidthQuotaTb: 30,
    status: 'Active'
  },
  {
    id: 'alloc-7',
    serverId: 'srv-112',
    serverHostname: 'mum1-backup-01.bharatdc.net',
    assetTag: 'BDC-SRV-112',
    clientId: 'client-5',
    clientName: 'Rural Health Record Archive',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    assignedDate: '2024-05-15',
    billingCycle: 'Annual',
    purpose: 'Cold Archive Health Document Store',
    bandwidthQuotaTb: 15,
    status: 'Active'
  }
];

export const INITIAL_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    ticketNumber: 'MNT-2026-081',
    title: 'UPS Battery Bank Inspection & Load Test',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    type: 'Preventive',
    priority: 'High',
    scheduledDate: '2026-09-24 02:00 IST',
    technician: 'Ramesh Sawant',
    status: 'Scheduled',
    notes: 'Routine quarterly check of uninterrupted power supply cells in Power Hall 2.'
  },
  {
    id: 'maint-2',
    ticketNumber: 'MNT-2026-082',
    title: 'Memory Diagnostic and DIMM Replacement',
    serverId: 'srv-104',
    serverHostname: 'mum1-node-04.bharatdc.net',
    rackNumber: 'Rack-A02',
    dataCenterName: 'BHARATDC Mumbai West (MUM-1)',
    type: 'Hardware Replacement',
    priority: 'Medium',
    scheduledDate: '2026-09-20 14:30 IST',
    technician: 'Amit Pathak',
    status: 'In Progress',
    notes: 'Replacing faulty DDR4 ECC 32GB stick in Slot B3.'
  },
  {
    id: 'maint-3',
    ticketNumber: 'MNT-2026-083',
    title: 'Hot Aisle Containment Air Filter Cleaning',
    rackNumber: 'Rack-C04',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    type: 'Preventive',
    priority: 'Low',
    scheduledDate: '2026-09-22 10:00 IST',
    technician: 'Vignesh Kumar',
    status: 'Scheduled',
    notes: 'Clean dust mesh and calibrate thermal intake sensors along Row C.'
  },
  {
    id: 'maint-4',
    ticketNumber: 'MNT-2026-084',
    title: 'Replace Tripped Power Supply Unit (PSU-1)',
    serverId: 'srv-109',
    serverHostname: 'blr1-edge-03.bharatdc.net',
    rackNumber: 'Rack-C04',
    dataCenterName: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    type: 'Emergency Repair',
    priority: 'Critical',
    scheduledDate: '2026-09-19 11:00 IST',
    technician: 'Karthik Raman',
    status: 'In Progress',
    notes: 'Hot-swap redundant PSU module to restore server power.'
  },
  {
    id: 'maint-5',
    ticketNumber: 'MNT-2026-079',
    title: 'Core Switch Firmware Patch Upgrade',
    dataCenterName: 'BHARATDC Delhi NCR (DEL-1)',
    type: 'Firmware Update',
    priority: 'Medium',
    scheduledDate: '2026-09-14 01:00 IST',
    technician: 'Pooja Kashyap',
    status: 'Completed',
    notes: 'Successfully patched security vulnerability CVE-2026-2011 on aggregation switches.'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    fullName: 'Rajesh Verma',
    email: 'rajesh.verma@bharatdc.in',
    role: 'Admin',
    assignedDataCenter: 'BHARATDC Mumbai West (MUM-1)',
    status: 'Active',
    lastLogin: '2026-09-18 09:14 IST',
    phone: '+91 98200 12345'
  },
  {
    id: 'usr-2',
    fullName: 'Pooja Kashyap',
    email: 'pooja.kashyap@bharatdc.in',
    role: 'Facility Operator',
    assignedDataCenter: 'BHARATDC Delhi NCR (DEL-1)',
    status: 'Active',
    lastLogin: '2026-09-18 08:30 IST',
    phone: '+91 98110 54321'
  },
  {
    id: 'usr-3',
    fullName: 'Karthik Raman',
    email: 'karthik.raman@bharatdc.in',
    role: 'Network Engineer',
    assignedDataCenter: 'BHARATDC Bengaluru Tech Hub (BLR-1)',
    status: 'Active',
    lastLogin: '2026-09-18 10:02 IST',
    phone: '+91 98450 67890'
  },
  {
    id: 'usr-4',
    fullName: 'Srinivas Rao',
    email: 'srinivas.rao@bharatdc.in',
    role: 'Technician',
    assignedDataCenter: 'BHARATDC Hyderabad HITEC (HYD-1)',
    status: 'Active',
    lastLogin: '2026-09-17 17:45 IST',
    phone: '+91 98660 11223'
  },
  {
    id: 'usr-5',
    fullName: 'Devendra Singhania',
    email: 'devendra.s@bharatdc.in',
    role: 'Auditor',
    assignedDataCenter: 'All Facilities',
    status: 'Active',
    lastLogin: '2026-09-16 11:20 IST',
    phone: '+91 97170 33445'
  }
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'act-1',
    timestamp: 'Today at 10:45 AM',
    userName: 'Rajesh Verma',
    action: 'Server Added',
    targetType: 'Server',
    targetName: 'BDC-SRV-111 (hyd1-logistics-02)',
    details: 'Commissioned in Rack-D01 with status Available'
  },
  {
    id: 'act-2',
    timestamp: 'Today at 09:30 AM',
    userName: 'Karthik Raman',
    action: 'Start Maintenance',
    targetType: 'Maintenance',
    targetName: 'MNT-2026-084',
    details: 'Started PSU diagnostic on server BDC-SRV-109'
  },
  {
    id: 'act-3',
    timestamp: 'Yesterday at 04:15 PM',
    userName: 'Pooja Kashyap',
    action: 'Server Allocated',
    targetType: 'Allocation',
    targetName: 'BDC-SRV-112',
    details: 'Assigned to client Rural Health Record Archive'
  },
  {
    id: 'act-4',
    timestamp: 'Yesterday at 02:00 PM',
    userName: 'Rajesh Verma',
    action: 'Rack Modified',
    targetType: 'Rack',
    targetName: 'Rack-A02',
    details: 'Updated power load telemetry and marked as Full'
  },
  {
    id: 'act-5',
    timestamp: '16 Sep 2026 at 11:30 AM',
    userName: 'Amit Pathak',
    action: 'Maintenance Scheduled',
    targetType: 'Maintenance',
    targetName: 'MNT-2026-082',
    details: 'Scheduled DIMM memory replacement for BDC-SRV-104'
  },
  {
    id: 'act-6',
    timestamp: '15 Sep 2026 at 03:20 PM',
    userName: 'Rajesh Verma',
    action: 'Client Onboarded',
    targetType: 'Client',
    targetName: 'FastPay Gateway Solutions',
    details: 'Approved contract terms and created client record'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Server Hardware Alert: BDC-SRV-109 Unpowered',
    message: 'Primary power supply unit (PSU-1) tripped in Bengaluru Data Center. Server marked Not Working.',
    timestamp: '15 minutes ago',
    read: false,
    priority: 'critical',
    category: 'Server'
  },
  {
    id: 'notif-2',
    title: 'Scheduled Maintenance Window Approaching',
    message: 'UPS Battery Bank test scheduled for Mumbai West (MUM-1) on 24 Sep at 02:00 IST.',
    timestamp: '2 hours ago',
    read: false,
    priority: 'warning',
    category: 'Maintenance'
  },
  {
    id: 'notif-3',
    title: 'High Rack Capacity Alert',
    message: 'Rack-A02 in Mumbai Data Center has reached maximum allocated capacity (42/42 units).',
    timestamp: '5 hours ago',
    read: true,
    priority: 'info',
    category: 'Facility'
  },
  {
    id: 'notif-4',
    title: 'New Client Server Allocation Activated',
    message: 'Server BDC-SRV-112 has been successfully linked to Rural Health Record Archive.',
    timestamp: '1 day ago',
    read: true,
    priority: 'info',
    category: 'Allocation'
  }
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep-1',
    title: 'Quarterly Infrastructure Capacity Report (Q3 2026)',
    type: 'Capacity',
    period: 'Q3 2026',
    generatedDate: '2026-09-15',
    generatedBy: 'Devendra Singhania',
    fileSize: '2.4 MB',
    status: 'Ready'
  },
  {
    id: 'rep-2',
    title: 'Monthly Server Usage & Allocation Summary',
    type: 'Server Usage',
    period: 'August 2026',
    generatedDate: '2026-09-01',
    generatedBy: 'Rajesh Verma',
    fileSize: '1.8 MB',
    status: 'Ready'
  },
  {
    id: 'rep-3',
    title: 'Facility Preventive Maintenance Log',
    type: 'Maintenance',
    period: 'Past 90 Days',
    generatedDate: '2026-09-10',
    generatedBy: 'Pooja Kashyap',
    fileSize: '840 KB',
    status: 'Ready'
  },
  {
    id: 'rep-4',
    title: 'Client SLA & Allocation Compliance Audit',
    type: 'Client Allocation',
    period: 'Year to Date 2026',
    generatedDate: '2026-08-30',
    generatedBy: 'Devendra Singhania',
    fileSize: '3.1 MB',
    status: 'Ready'
  }
];
